### ISSUE TITLE
Error on startup with Ubuntu 16.04

### ISSUE THREAD

**Issue by lhurt** [Akkadius/glass-isc-dhcp#10]
Hi,
I'd love to use glass but I'm not able to start it.

Output is

```
> > dhcpd-glass@0.0.0 start /opt/glass-isc-dhcp
> > node ./bin/www
> 
> /opt/glass-isc-dhcp/app.js:674
> let transporter = nodemailer.createTransport({
> ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:414:25)
>     at Object.Module._extensions..js (module.js:442:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:311:12)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at Object.<anonymous> (/opt/glass-isc-dhcp/bin/www:7:11)
>     at Module._compile (module.js:435:26)
>     at Object.Module._extensions..js (module.js:442:10)
> 
> npm ERR! Linux 4.4.0-119-generic
> npm ERR! argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "start"
> npm ERR! node v4.2.2
> npm ERR! npm  v2.14.7
> npm ERR! code ELIFECYCLE
> npm ERR! dhcpd-glass@0.0.0 start: `node ./bin/www`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the dhcpd-glass@0.0.0 start script 'node ./bin/www'.
> npm ERR! This is most likely a problem with the dhcpd-glass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node ./bin/www
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls dhcpd-glass
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /opt/glass-isc-dhcp/npm-debug.log
```

and npm-debug.log is
```
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v4.2.2/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v4.2.2/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart dhcpd-glass@0.0.0
6 info start dhcpd-glass@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info dhcpd-glass@0.0.0 Failed to exec start script
9 verbose stack Error: dhcpd-glass@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v4.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid dhcpd-glass@0.0.0
11 verbose cwd /opt/glass-isc-dhcp
12 error Linux 4.4.0-119-generic
13 error argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "start"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error dhcpd-glass@0.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the dhcpd-glass@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the dhcpd-glass package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get their info via:
18 error     npm owner ls dhcpd-glass
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

any idea?

Thanks

**Comment by Akkadius** [comment]
Make sure your node version is up to date

**Comment by tobbe-eklov** [comment]
I have similar problem in Ubuntu 16.04 and nodejs 4.2.6

let transporter = nodemailer.createTransport({
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/glass-isc-dhcp/bin/www:7:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

/Tobbe
