### ISSUE TITLE
Error starting up glass_start.sh nodemailer.createTransport SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Sharkrit** [Akkadius/glass-isc-dhcp#3]
Hi @Akkadius ,
I try to install Glass on my CentOS v6.5, after deployed, I've got this error when execute ```sudo npm start``` or ```./glass_start.sh```

It keeps appear this errors in /opt/glass-isc-dhcp/logs/glass-error.log
```
/opt/glass-isc-dhcp/app.js:673
let transporter = nodemailer.createTransport({
    ^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/glass-isc-dhcp/bin/www:7:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
error: Forever detected script exited with code: 8
```

Can you guide me how to troubleshoot this error?
Big Thanks in Advance,
Sharkrit

**Comment by Akkadius** [comment]
Hello @Sharkrit - you may want to look into updating your nodeJS

https://nodejs.org/en/download/package-manager/

After doing so - try running glass
