### ISSUE TITLE
During fresh install and Starting of glass-isc-dhcp on raspberry pi 3b

### ISSUE THREAD

**Issue by mkopnsrc** [Akkadius/glass-isc-dhcp#33]
glass is freshly installed and starting up but failing and gives following error output. Can you please help?

/bin/sh: 1: ./bin/dhcpd-pools: Exec format error
child_process.js:645
    throw err;
    ^

Error: Command failed: ./bin/dhcpd-pools -c /etc/dhcp/dhcpd.conf -l /var/lib/dhcp/dhcpd.leases -f j -A -s e
/bin/sh: 1: ./bin/dhcpd-pools: Exec format error

    at checkExecSyncError (child_process.js:602:13)
    at execSync (child_process.js:642:13)
    at Timeout._onTimeout (/opt/glass-isc-dhcp/app.js:322:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by Akkadius** [comment]
This is because `dhcpd-pools` needs to be compiled on platforms that don't work out of the box

See: https://github.com/Akkadius/glass-isc-dhcp#building-dhcpd-pools-optional
