### ISSUE TITLE
Web interface crashes on view

### ISSUE THREAD

**Issue by koeus88** [Akkadius/glass-isc-dhcp#36]
A second or two after viewing the glass interface the http process will crash and start over a few seconds later. When this happens this log entry is created. 

```
Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)
```

On Centos 7 with Node 8.15

**Comment by koeus88** [comment]
Issue ended up being an IPS that was triggering a rule due to port 8080. I added an exception that resolved the issue. Closing issue.
