### ISSUE TITLE
Failed to exec start script - Possible Syntax error

### ISSUE THREAD

**Issue by Guerbie** [Akkadius/glass-isc-dhcp#4]
For starters, absolutely love this work! Have been looking for something like this for months as part of a home lab project. 

Unfortunately with my absolutely limited skillset I have come across a script start error that I just cant seem to get past. It may well be my own stupidity that is the error but in the event there is actually an error with the script I would appreciate your advice.

The logfile is:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dhcpd-glass@0.0.0~prestart: dhcpd-glass@0.0.0
6 info lifecycle dhcpd-glass@0.0.0~start: dhcpd-glass@0.0.0
7 verbose lifecycle dhcpd-glass@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle dhcpd-glass@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/glass-isc-dhcp/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle dhcpd-glass@0.0.0~start: CWD: /opt/glass-isc-dhcp
10 silly lifecycle dhcpd-glass@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
11 silly lifecycle dhcpd-glass@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle dhcpd-glass@0.0.0~start: Failed to exec start script
13 verbose stack Error: dhcpd-glass@0.0.0 start: `node ./bin/www`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid dhcpd-glass@0.0.0
15 verbose cwd /opt/glass-isc-dhcp
16 verbose Linux 4.4.38-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error dhcpd-glass@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the dhcpd-glass@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Akkadius** [comment]
Hey @Guerbie what distro is this on?

**Comment by Akkadius** [comment]
The stack is not very revealing - I would make sure that node is up to date and issue a `npm update` as well and let me know what you see as a result of that

**Comment by Guerbie** [comment]
Hi Akkadius,

After dozens of attempts (and a few VMs) I finally managed to get it running on Raspbian. I then went to try and break a few things and see if I could re-trigger the errors. Looks like anytime there is something wrong with an underlying services the startup script will throw this error. I can even get this error when there is a misconfiguration with the DHCP conf, or one of my IP addresses are not properly set (in this case I had to disable my fallover wifi connection).

At present Glass is loading correctly, although a lot of the outputs are not corrrectly showing on the home screen (leases are accurate and reflecting actual renewals properly). This is likely user error, so I am working through them one by one.

Absolutely awesome work, owe you a few beers at this rate.

Regards,
Guerbie
