### ISSUE TITLE
NodeJS 8.x is Deprecated

### ISSUE THREAD

**Issue by firthmj** [Akkadius/glass-isc-dhcp#57]
Hi,

The version of NodeJS suggested in the installation instructions (8.x Carbon) is now deprecated.

Following the installation instructions gives a big red warning to this effect.

Does Glass support either NodeJS 10.x or 12.x, which are the newer LTS releases?

**Comment by tmacgbay** [comment]
I have it working with v10.19.0

**Comment by lgwapnitsky** [comment]
doesn't work with 14. will try with 10 later.  thank you for the info

**Comment by atownsend247** [comment]
I have it working successfully on version 12.20.0

**Comment by PartTimeJS** [comment]
I am also running it on node 12 without issues.

**Comment by pmjufo** [comment]
Hi,
installed it today on a raspi which has Node.js v10.23.1 installed.

during install lot of warning messages including:

npm WARN npm npm does not support Node.js v10.23.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.

could nevertheless access glass on port 3000 but after some clicks it crashed with:

[Glass Server] Slack alert triggered, but no webhook configured...
[Glass Server] Loading E-Mail template...
[Glass Server] Loading E-Mail template... DONE...
[Glass Server] Sending E-Mail Alert...

/bin/sh: 1: ./bin/dhcpd-pools: Exec format error
child_process.js:669
    throw err;
    ^

Error: Command failed: ./bin/dhcpd-pools -c /etc/dhcp/dhcpd.conf -l /var/lib/dhcp/dhcpd.leases -f j -A -s e
/bin/sh: 1: ./bin/dhcpd-pools: Exec format error

    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Timeout._onTimeout (/opt/glass-isc-dhcp/app.js:322:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dhcpd-glass@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dhcpd-glass@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-12T16_24_53_259Z-debug.log
