### ISSUE TITLE
Error after some minutes

### ISSUE THREAD

**Issue by hismastersvoice** [Akkadius/glass-isc-dhcp#9]
Hi,

I try to run the Web UI on a Raspberry 3 and Raspian lite.
After some Miuntes of runing I get the following error.

GET /get_stats 500 33.057 ms - 1004
RangeError: Invalid status code: 2
    at ServerResponse.writeHead (_http_server.js:194:11)
    at ServerResponse.writeHead (/opt/glass-isc-dhcp/node_modules/morgan/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:185:8)
    at write_ (_http_outgoing.js:632:9)
    at ServerResponse.end (_http_outgoing.js:751:5)
    at ServerResponse.send (/opt/glass-isc-dhcp/node_modules/express/lib/response.js:211:10)
    at /opt/glass-isc-dhcp/app.js:75:9
    at Layer.handle_error (/opt/glass-isc-dhcp/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/glass-isc-dhcp/node_modules/express/lib/router/index.js:315:13)
    at /opt/glass-isc-dhcp/node_modules/express/lib/router/index.js:284:7
GET /glass_settings?v_ajax 304 9.844 ms - -
/bin/sh: 1: ./bin/dhcpd-pools: Exec format error
child_process.js:644
    throw err;
    ^

Error: Command failed: ./bin/dhcpd-pools -c /etc/dhcp/dhcpd.conf -l /var/lib/dhcp/dhcpd.leases -f j -A -s e
/bin/sh: 1: ./bin/dhcpd-pools: Exec format error

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Timeout._onTimeout (/opt/glass-isc-dhcp/app.js:555:22)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dhcpd-glass@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dhcpd-glass@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-25T16_29_09_440Z-debug.log

I can´t find the error, so hopfully you can help me.

Dieter

**Comment by SenSourceAdmin** [comment]
@hismastersvoice was having the same trouble. on raspberry pi you have to build the `dhcpd-pools` since it was compiled for a different processor architecture. follow the instructions in the readme, but you'll also need;

```sh
sudo apt-get install -y autoconf automake
```

**before** you execute `./bootstrap`

**Comment by jdforsythe** [comment]
@hismastersvoice was having the same trouble. on raspberry pi you have to build the `dhcpd-pools` since it was compiled for a different processor architecture. follow the instructions in the readme, but you'll also need;

```sh
sudo apt-get install -y autoconf automake
```

**before** you execute `./bootstrap`

**Comment by hismastersvoice** [comment]
@jdforsythe 
Now it works perfect... 
I already tryed to compile it, but i got a lot for errors. 
THANKS...

**Comment by seans11** [comment]
> sudo apt-get install -y unzip libtool automake autoconf

Just an addition for dependencies; I had to add `make` since I was using a minimal install of Centos on Pi.  

On Centos it was:
```shell
sudo yum install -y unzip libtool automake autoconf make
